In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./Files/survey_results.csv')
df

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89179,89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89180,89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89181,89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89182,89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89183,89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [11]:
filt = df['ConvertedCompYearly'] > 200000
df.loc[filt,['YearsCode','Country','ConvertedCompYearly','Industry','LanguageHaveWorkedWith']]

,YearsCode,Country,ConvertedCompYearly,Industry,LanguageHaveWorkedWith
1,18,United States of America,285000.0,"Information Services, IT, Software Development...",HTML/CSS;JavaScript;Python
2,27,United States of America,250000.0,"Information Services, IT, Software Development...",Bash/Shell (all shells);Go
30,24,Australia,237974.0,NaN,Go;JavaScript;Python
121,20,United States of America,200990.0,"Information Services, IT, Software Development...",Go;HTML/CSS;JavaScript;PowerShell;Python;Rust
248,6,United Kingdom of Great Britain and Northern I...,223449.0,"Information Services, IT, Software Development...",Bash/Shell (all shells);Go;HTML/CSS;JavaScript...
...,...,...,...,...,...
89133,14,United States of America,500000.0,Other,C#;JavaScript;SQL;TypeScript
89137,42,Kenya,250000.0,NaN,Bash/Shell (all shells);Go;HTML/CSS;JavaScript
89139,13,United States of America,215000.0,NaN,Bash/Shell (all shells);C++;JavaScript;Python
89141,14,United States of America,250000.0,Financial Services,C#;C++;Java;Ruby;Scala;SQL;TypeScript
89157,17,Canada,319711.0,"Information Services, IT, Software Development...",Java;Kotlin

In [15]:
filt = df['LanguageHaveWorkedWith'].str.contains('Python', na = False)
df.loc[filt,['YearsCode','Country','ConvertedCompYearly','Industry','LanguageHaveWorkedWith']]

,YearsCode,Country,ConvertedCompYearly,Industry,LanguageHaveWorkedWith
1,18,United States of America,285000.0,"Information Services, IT, Software Development...",HTML/CSS;JavaScript;Python
7,5,United States of America,80000.0,Financial Services,Go;HTML/CSS;JavaScript;Python;Rust;SQL;TypeScript
9,6,India,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript
10,14,United States of America,NaN,Other,C#;C++;HTML/CSS;JavaScript;Python
11,10,Australia,78003.0,NaN,C#;HTML/CSS;JavaScript;Kotlin;PowerShell;Pytho...
...,...,...,...,...,...
89172,38,Spain,NaN,"Information Services, IT, Software Development...",Bash/Shell (all shells);HTML/CSS;JavaScript;Pe...
89176,2,Greece,NaN,NaN,HTML/CSS;Java;JavaScript;PHP;Python;SQL;TypeSc...
89180,5,Romania,NaN,NaN,Dart;Java;Python;SQL
89181,10,Israel,NaN,NaN,Assembly;Bash/Shell (all shells);C;C#;Python;R...
89182,3,Switzerland,NaN,NaN,Bash/Shell (all shells);C#;HTML/CSS;Java;JavaS...

In [16]:
filt = df['Country'].isin(['Australia','United States Of America' , 'India'])
df.loc[filt,['YearsCode','Country','ConvertedCompYearly','Industry']]

,YearsCode,Country,ConvertedCompYearly,Industry
9,6,India,NaN,NaN
11,10,Australia,78003.0,NaN
30,24,Australia,237974.0,NaN
49,15,Australia,NaN,NaN
66,10,India,41197.0,NaN
...,...,...,...,...
89121,4,India,NaN,NaN
89123,10,Australia,330520.0,Financial Services
89164,6,India,NaN,Financial Services
89165,6,India,NaN,"Information Services, IT, Software Development..."
89167,6,India,15752.0,Retail and Consumer Services

In [17]:
filt = df['Country'].isin(['Australia','United States Of America' , 'India']) & df['ConvertedCompYearly'] > 200000
df.loc[filt,['YearsCode','Country','ConvertedCompYearly','Industry']]

Empty DataFrame
Columns: [YearsCode, Country, ConvertedCompYearly, Industry]
Index: []

In [18]:
df.filter(items = ['YearCode','Country','Industry'])

,Country,Industry
0,NaN,NaN
1,United States of America,"Information Services, IT, Software Development..."
2,United States of America,"Information Services, IT, Software Development..."
3,United States of America,NaN
4,Philippines,Other
...,...,...
89179,Brazil,NaN
89180,Romania,NaN
89181,Israel,NaN
89182,Switzerland,NaN
89183,"Iran, Islamic Republic of...","Information Services, IT, Software Development..."